- index.html
> [Fix] 경로 문제 해결

- Frontend/src/App.tsx
- 4분마다 토큰 갱신 요청하도록 수정
- close #123
- resolves #456
| 이미지 | 이미지 |
> [Fix] 토큰 갱신 로직 수정

- Frontend/src/app.json
- Frontend/src/package-lock.json
- Frontend/src/package.json
- Frontend/src/screens/DailyTopic.tsx
- Frontend/src/screens/SignUp/SignUpStep1.tsx
- Frontend/src/screens/SignUp/SignUpStep3.tsx
- Frontend/src/styles/dailyTopicStyles.ts
- Frontend/src/styles/signUpStyles.ts
- 입력창이 키보드에의해 가려지는 오류 수정
- #101 
| 이미지 | 이미지 |
> [Fix] 입력창 키보드에 가려지는 오류 수정

- src/main/kotlin/kr/ac/kookmin/wuung/controller/QuestsController.kt
- src/main/kotlin/kr/ac/kookmin/wuung/model/User.kt
- src/main/kotlin/kr/ac/kookmin/wuung/model/UserQuestStage.kt
- src/main/kotlin/kr/ac/kookmin/wuung/model/UserQuestStages.kt
- src/main/kotlin/kr/ac/kookmin/wuung/model/UserQuests.kt
- src/main/kotlin/kr/ac/kookmin/wuung/repository/UserQuestStageRepository.kt
퀘스트의 주 진행상황, 부 진행상황을 확인할 수 있는 API 추가
- close #108 
- [ ✅] 코드가 정상적으로 동작하며 빌드에 통과합니다.
- [ ✅] 테스트를 추가했거나, 기존 테스트가 충분합니다.
- [✅ ] 코드 스타일 가이드를 따랐습니다.
- [ ✅] PR 내용에 맞는 커밋 메시지를 작성했습니다.
- [ ✅] 셀프 리뷰를 완료했습니다.
Quest API 요구사항 맞게 리팩토링했습니다.
> [Refactor] Quest API 수정

- Frontend/src/API/topicAPI.ts
- Frontend/src/screens/DailyTopic.tsx
- Frontend/src/styles/dailyTopicStyles.ts
-챗봇 대화 API 연결
#110 
- 그날 하루 리미트 대화를 보낸 마지막 답변 기록 추가 예정
- 리미트 종료시 일기 화면으로 가게끔 추가 예정
> [Feat] 매일 1주제 API 연결

- Frontend/src/App.tsx
- Frontend/src/components/HeaderTitle.tsx
- Frontend/src/hooks/useSecondPasswordGuard.ts
- Frontend/src/screens/Calendar.tsx
- Frontend/src/screens/FormalDiagnosis/FormalDiagnosis.tsx
- Frontend/src/screens/SignUp/SignUpStep3.tsx
- Frontend/src/screens/UserInfo.tsx
- Frontend/src/styles/headerTitleStyles.ts
- 캘린더 및 정식진단에 2차 비밀번호 연결
- 2차 비밀번호 타입 개선
- 숫자키보드 자동으로 내려가게 수정
- close #123
- resolves #456
| 이미지 | 이미지 |
> [Feat] 2차 비밀번호 연결 및 키보드 자동 내려가는 기능 추가

- Frontend/src/App.tsx
- Frontend/src/screens/FormalDiagnosis/FormalDiagnsis_result.tsx
- Frontend/src/styles/formalDiagnsisResultStyles.ts
> [Feat] 검사 결과 화면 생성

- src/main/kotlin/kr/ac/kookmin/wuung/controller/QuestsController.kt
요구사항 수정 완료
last API 반환 양식 수정
- close #127 
- [✅] 코드가 정상적으로 동작하며 빌드에 통과합니다.
- [✅] 테스트를 추가했거나, 기존 테스트가 충분합니다.
- [✅] 코드 스타일 가이드를 따랐습니다.
- [✅] PR 내용에 맞는 커밋 메시지를 작성했습니다.
- [✅] 셀프 리뷰를 완료했습니다.
last API는 사용자가 진행 중인 퀘스트의 단계를 표현하는 데이터를 가져오는 API입니다.
> [Fix] Quest last API 수정 완료 #127

- Frontend/src/API/diagnosisAPI.ts
- Frontend/src/App.tsx
- Frontend/src/components/SurveyQuestion.tsx
- Frontend/src/screens/FormalDiagnosis/FormalDiagnosis.tsx
- Frontend/src/screens/FormalDiagnosis/FormalDiagnosis_survey.tsx
- Frontend/src/screens/FormalDiagnosis/FormalDiagnsis_result.tsx
- 진단 결과 저장 api 연결
-  정보 받는 api 연결
- 호출 방식 개선
- #123
| 이미지 | 이미지 |
> [Feat] 진단 결과 저장 api 연결 및 정보 받는 api 연결

- Frontend/src/API/diagnosisAPI.ts
- Frontend/src/components/EmotionChartBox.tsx
- Frontend/src/components/MethodCard.tsx
- Frontend/src/hooks/useDiagnosisColor.ts
- Frontend/src/package-lock.json
- Frontend/src/package.json
- Frontend/src/screens/FormalDiagnosis/FormalDiagnosis.tsx
- Frontend/src/screens/FormalDiagnosis/FormalDiagnosis_survey.tsx
- Frontend/src/screens/FormalDiagnosis/FormalDiagnsis_result.tsx
- Frontend/src/styles/emotionChartBoxStyles.ts
- Frontend/src/styles/formalDiagnsisResultStyles.ts
- Frontend/src/styles/methodCardStyles.ts
- 진단결과 보여주는 그래프 생성 (2주간)
- close #123
| 이미지 | 이미지 |
> [Feat] 진단 결과 그래프 생성

- src/main/kotlin/kr/ac/kookmin/wuung/controller/QuestsController.kt
- src/main/kotlin/kr/ac/kookmin/wuung/model/UserQuests.kt
- src/main/kotlin/kr/ac/kookmin/wuung/service/UserQuestS3Service.kt
- src/main/resources/application.yml
- Add UserQuests add photo service, logics.
- #121 
| 이미지 | 이미지 |
- None.
> [feature] UserQuests add photo service, logics.

- src/main/kotlin/kr/ac/kookmin/wuung/controller/QuestsController.kt
- src/main/kotlin/kr/ac/kookmin/wuung/model/LifeQuotes.kt
- src/main/kotlin/kr/ac/kookmin/wuung/repository/LifeQuoteRepository.kt
GET /quests/quoto로 API 요청시 명언 반환
- close #136
- [✅ ] 코드가 정상적으로 동작하며 빌드에 통과합니다.
- [✅ ] 테스트를 추가했거나, 기존 테스트가 충분합니다.
- [✅ ] 코드 스타일 가이드를 따랐습니다.
- [✅ ] PR 내용에 맞는 커밋 메시지를 작성했습니다.
- [✅ ] 셀프 리뷰를 완료했습니다.
> [Feat] 명언 API 구현

- src/main/kotlin/kr/ac/kookmin/wuung/controller/EtcController.kt
프론트 편의를 위한 ETC API 반환 양식 수정
- resolves #138
- [✅] 코드가 정상적으로 동작하며 빌드에 통과합니다.
- [✅] 테스트를 추가했거나, 기존 테스트가 충분합니다.
- [✅] 코드 스타일 가이드를 따랐습니다.
- [✅] PR 내용에 맞는 커밋 메시지를 작성했습니다.
- [✅] 셀프 리뷰를 완료했습니다.
@janeny117 요구 사항 반영했습니다.
> [Refactor] ETC API 반환 양식 수정

- Frontend/src/screens/Calendar.tsx
- Frontend/src/styles/calendarStyles.ts
- 예: 로그인 로직 수정 및 JWT 토큰 발급 방식 개선
- 예: React Native 화면 전환 시 애니메이션 추가
- close #123
- resolves #456
| 이미지 | 이미지 |
> [Feat] 빈배열 처리

- .gitignore
- build.gradle.kts
- src/main/kotlin/kr/ac/kookmin/wuung/WuungApplication.kt
- src/main/kotlin/kr/ac/kookmin/wuung/config/SecurityConfig.kt
- src/main/kotlin/kr/ac/kookmin/wuung/controller/LoginController.kt
- src/main/kotlin/kr/ac/kookmin/wuung/model/Diagnosis.kt
- src/main/kotlin/kr/ac/kookmin/wuung/model/DiagnosisText.kt
- src/main/kotlin/kr/ac/kookmin/wuung/model/Quests.kt
- src/main/kotlin/kr/ac/kookmin/wuung/model/Test.kt
- src/main/kotlin/kr/ac/kookmin/wuung/model/TopicFeedback.kt
- src/main/kotlin/kr/ac/kookmin/wuung/model/User.kt
- src/main/kotlin/kr/ac/kookmin/wuung/model/UserQuests.kt
- src/main/kotlin/kr/ac/kookmin/wuung/repository/IntegrityChallengeRepository.kt
- src/main/kotlin/kr/ac/kookmin/wuung/repository/RefreshTokenRepository.kt
- src/main/kotlin/kr/ac/kookmin/wuung/security/ExceptionHandler.kt
- src/main/kotlin/kr/ac/kookmin/wuung/service/IntegrityService.kt
- src/main/resources/application.yml
- src/main/resources/templates/login.html
- admin page with password login
- None
| 이미지 | 이미지 |
- `/admin` 으로 접근시 ADMIN 권한이 있는 유저로 로그인해야 합니다.
- 해당 유저로 로그인시 DB 관리가 가능한 UI가 보여집니다.
> [feature] admin page with password login

- Frontend/src/components/FloatingButton.tsx
- Frontend/src/screens/DailyTopic.tsx
- Frontend/src/styles/floatingButtonStyles.ts
- 매일 1주제 접근시, 답변 5번 다 했을시에 오류 수정
- 그날 매일 1주제 완수 안했을 경우 사용자에게 빨간 알림으로 상태 보여줌
#110
> [Feat] 매일 1주제 오류 수정 및 완수/미완수 상태 판별

- src/main/kotlin/kr/ac/kookmin/wuung/controller/QuestsController.kt
- UserQuest record save method added.
- None
| 이미지 | 이미지 |
- None.
> [hotfix] record save added.

- src/main/kotlin/kr/ac/kookmin/wuung/controller/AuthController.kt
- src/main/kotlin/kr/ac/kookmin/wuung/controller/QuestsController.kt
- quest/auth photo related hotfix.
- None
| 이미지 | 이미지 |
- 이미지 관련 필드가 null로 주어지는 경우를 수정하였습니다.
> [hotfix] quest/auth photo related hotfix.

- src/main/kotlin/kr/ac/kookmin/wuung/controller/AuthController.kt
- src/main/kotlin/kr/ac/kookmin/wuung/service/TokenService.kt
- if refreshToken expires at least 1 day, refresh RefreshToken
- None
| 이미지 | 이미지 |
- 이 PR로 인해 refreshToken이 1일 내 만료 예정이라면 새로운 refreshToken을 발급합니다.
> [hotfix] if refreshToken expires at least 1 day, refresh RefreshToken

- API.md
- openapi.json
- src/main/kotlin/kr/ac/kookmin/wuung/controller/PotController.kt
- src/main/kotlin/kr/ac/kookmin/wuung/controller/QuestsController.kt
- src/main/kotlin/kr/ac/kookmin/wuung/model/Pot.kt
- src/main/kotlin/kr/ac/kookmin/wuung/model/Record.kt
- src/main/kotlin/kr/ac/kookmin/wuung/repository/UserRepository.kt
- 출시 준비를 위한 Develop to master merge.
- None.
| 이미지 | 이미지 |
- None.
> [release] develop merge to master

- Frontend/src/App.tsx
- Frontend/src/components/SimpleResult.tsx
- Frontend/src/screens/DailyTopic.tsx
- Frontend/src/screens/Home.tsx
- Frontend/src/screens/SignIn.tsx
- Frontend/src/styles/homeStyles.ts
- 약식검사 결과 말풍선 생성
- close #123
- resolves #456
| 이미지 | 이미지 |
> [Feat] 약식검사 결과 말풍선 생성

- Frontend/src/components/Tree.tsx
- Frontend/src/screens/Quest/Quest.tsx
- Frontend/src/screens/Quest/Quest_stage.tsx
- quest_emotion으로 접근시 클로버 아이콘 수정
- quest_stage와 quest_emotion 연결
#174
> [Feat] quest_emotion 연결

- Frontend/src/App.tsx
- Frontend/src/components/Quest_emotionBox.tsx
- Frontend/src/components/Tree.tsx
- Frontend/src/package-lock.json
- Frontend/src/package.json
- Frontend/src/screens/Quest/Quest.tsx
- Frontend/src/screens/Quest/Quest_emotion.tsx
- Frontend/src/screens/Quest/Quest_stage.tsx
- Frontend/src/styles/questEmotionChartStyles.ts
> [Feat] 퀘스트 이모션 연결

- .idea/sqldialects.xml
- src/main/kotlin/kr/ac/kookmin/wuung/controller/PotController.kt
피드백 의견 반영
- 여러 쿠폰 사용 로직 추가
- close #191
- [✅] 코드가 정상적으로 동작하며 빌드에 통과합니다.
- [✅] 테스트를 추가했거나, 기존 테스트가 충분합니다.
- [✅] 코드 스타일 가이드를 따랐습니다.
- [✅] PR 내용에 맞는 커밋 메시지를 작성했습니다.
- [✅] 셀프 리뷰를 완료했습니다.
> [refactor] 여러 쿠폰 사용 로직 추가
